<testsuite name="sample.Testing Feature configuration" tests="1" errors="1" failures="0" skipped="0" time="63.509312" timestamp="2021-06-01T16:15:35.692495" hostname="Lnvictor"><testcase classname="sample.Testing Feature configuration" name="Verifying Homepage" status="failed" time="63.509312"><error type="TimeoutException" message="Message: &#10;">
<![CDATA[
Failing step: And crio um todolist com os dados ... failed in 50.570s
  | Name | Value                 |
  | nome | exemplo todolist      |
  | desc | testando com selenium |
  | data | 16032021              |
Location: features/sample.feature:12
Traceback (most recent call last):
  File "/home/victor/projects/Ktask-Automated-Tests/.venv/lib/python3.9/site-packages/behave/model.py", line 1329, in run
    match.run(runner.context)
  File "/home/victor/projects/Ktask-Automated-Tests/.venv/lib/python3.9/site-packages/behave/matchers.py", line 98, in run
    self.func(context, *args, **kwargs)
  File "features/steps/sample.py", line 50, in _
    el = self.wait.until(
  File "/home/victor/projects/Ktask-Automated-Tests/.venv/lib/python3.9/site-packages/selenium/webdriver/support/wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 

]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Verifying Homepage
    Given I access my application on browser ... passed in 5.188s
    When I click on Entrar button ... passed in 3.961s
    And Log in with "xileyaf341@relumyx.com" account and "Ktask@123" password ... passed in 1.116s
    Then devo estar logado ... passed in 2.674s
    And crio um todolist com os dados ... failed in 50.570s
      | Name | Value                 |
      | nome | exemplo todolist      |
      | desc | testando com selenium |
      | data | 16032021              |

@scenario.end
--------------------------------------------------------------------------------
]]>
</system-out></testcase></testsuite>